### ISSUE TITLE
Convert to a BepInEx mod

### ISSUE THREAD

**Issue by ohayo** [y2k04/mcgp#1]
That way you could remove the mod at any time, or prevent it from loading with a configuration option possibly, having no need for you to keep backups of anything related to the game files.

Also I looked through your github repositories, and you seem pretty experienced at modding other games.
Is it possible that I could get your discord?

**Comment by ohayo** [comment]
You could also just hook deserialization of the lines* (RenpyParser.VGPrompter.DataHolders.Lines)

**Comment by y2k04** [comment]
I'm actually still learning about BepInEx with making my own mod for TCG Card Shop Simulator. When I get more familiar with how to use it, I will revisit this mod for DDLC+.

**Comment by ohayo** [comment]
I could also help you out, maybe make a new branch which experiments with it?

**Comment by ohayo** [comment]
I have been experimenting with DDLC+ for years, and I would love to help out people with modding it

**Comment by ohayo** [comment]
If you have any other method of contact, I would love it as I'm working on a [ddlc+ mod loader](https://github.com/ddlcplus/doki) (It is so unbelievably messy at the moment) and i'm curious if you'd like to be on the team

**Comment by y2k04** [comment]
> If you have any other method of contact, I would love it as I'm working on a [ddlc+ mod loader](https://github.com/ddlcplus/doki) (It is so unbelievably messy at the moment) and i'm curious if you'd like to be on the team

[redacted]

**Comment by ohayo** [comment]
Hi! I have added you on discord, my username has p.ea in it (I can't give it all out due to a cyberstalker :sob:)
